version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker:
    image: python:3.9-slim
    container_name: celery_worker
    command: >
      sh -c "pip install -r /app/requirements.txt && celery -A celery worker --loglevel=info"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./celery_worker:/app  # Mount your local directory with Celery code
    working_dir: /app
    depends_on:
      - redis
